/*
* (c) Copyright, Real-Time Innovations, 2020.  All rights reserved.
* RTI grants Licensee a license to use, modify, compile, and create derivative
* works of the software solely for use with RTI Connext DDS. Licensee may
* redistribute copies of the software provided that all such copies are subject
* to this license. The software is provided "as is", with no warranty of any
* type, including any warranty for fitness for any purpose. RTI is under no
* obligation to maintain or support the software. RTI shall not be liable for
* any incidental or consequential damages arising out of the use or inability
* to use the software.
*/

/* hello_world_publisher.cxx

A publication of data of type HelloMessage

rtiddsgen -language C++ -example <arch> hello_world.idl

Example publication of type HelloMessage automatically generated by
'rtiddsgen'. To test it, follow these steps:

(1) Compile this file and the example subscription.

(2) Start the subscription

(3) Start the publication

(4) [Optional] Specify the list of discovery initial peers and
multicast receive addresses via an environment variable or a file
(in the current working directory) called NDDS_DISCOVERY_PEERS.

You can run any number of publisher and subscriber programs, and can
add and remove them dynamically from the domain.
*/

#include <stdio.h>
#include <stdlib.h>

#include "hello_world.h"
#include "hello_worldSupport.h"
#include "ndds/ndds_cpp.h"

static int shutdown(
        DDSDomainParticipant *participant,
        const char *shutdown_message,
        int status);


int publisher_run(int domain_id, int sample_count)
{
    // Connext DDS setup
    // -----------------
    // A DomainParticipant allows an application to begin communicating in
    // a DDS domain. Typically there is one DomainParticipant per application.
    // DomainParticipant QoS is configured in USER_QOS_PROFILES.xml
    DDSDomainParticipant *participant =
            DDSTheParticipantFactory->create_participant(
                    domain_id,
                    DDS_PARTICIPANT_QOS_DEFAULT,
                    NULL /* listener */,
                    DDS_STATUS_MASK_NONE);
    if (participant == NULL) {
        return shutdown(participant, "create_participant error", -1);
    }

    // A Publisher allows an application to create one or more DataWriters
    // Publisher QoS is configured in USER_QOS_PROFILES.xml
    DDSPublisher *publisher = participant->create_publisher(
            DDS_PUBLISHER_QOS_DEFAULT,
            NULL /* listener */,
            DDS_STATUS_MASK_NONE);
    if (publisher == NULL) {
        return shutdown(participant, "create_publisher error", -1);
    }

    // Register the datatype to use when creating the Topic
    const char *type_name = HelloMessageTypeSupport::get_type_name();
    DDS_ReturnCode_t retcode =
            HelloMessageTypeSupport::register_type(participant, type_name);
    if (retcode != DDS_RETCODE_OK) {
        return shutdown(participant, "register_type error", -1);
    }

    // A Topic has a name and a datatype. Create a Topic called
    // "Example HelloMessage" with your registered data type
    DDSTopic *topic = participant->create_topic(
            "Example HelloMessage",
            type_name,
            DDS_TOPIC_QOS_DEFAULT,
            NULL /* listener */,
            DDS_STATUS_MASK_NONE);
    if (topic == NULL) {
        return shutdown(participant, "create_topic error", -1);
    }

    // This DataWriter writes data on Topic "Example HelloMessage"
    // DataWriter QoS is configured in USER_QOS_PROFILES.xml
    DDSDataWriter *writer = publisher->create_datawriter(
            topic,
            DDS_DATAWRITER_QOS_DEFAULT,
            NULL /* listener */,
            DDS_STATUS_MASK_NONE);
    if (writer == NULL) {
        return shutdown(participant, "create_datawriter error", -1);
    }
    // A narrow is a cast from a generic DataWriter to one that is specific
    // to your type. Use the type specific DataWriter to write() 
    HelloMessageDataWriter *HelloMessage_writer =
            HelloMessageDataWriter::narrow(writer);
    if (HelloMessage_writer == NULL) {
        return shutdown(participant, "DataWriter narrow error", -1);
    }

    // Create data sample for writing
    HelloMessage *sample = HelloMessageTypeSupport::create_data();
    if (sample == NULL) {
        return shutdown(
                participant,
                "HelloMessageTypeSupport::create_data error",
                -1);
    }

    // Main loop, write data
    // ---------------------
    for (int count = 0; (sample_count == 0) || (count < sample_count);
         ++count) {
        // Modify the data to be written here

        printf("Writing HelloMessage, count %d\n", count);
        retcode = HelloMessage_writer->write(*sample, DDS_HANDLE_NIL);
        if (retcode != DDS_RETCODE_OK) {
            fprintf(stderr, "write error %d\n", retcode);
        }

        // Send every 4 seconds
        DDS_Duration_t send_period = { 4, 0 };
        NDDSUtility::sleep(send_period);
    }

    // Cleanup
    // -------
    // Delete data sample
    retcode = HelloMessageTypeSupport::delete_data(sample);
    if (retcode != DDS_RETCODE_OK) {
        fprintf(stderr,
                "HelloMessageTypeSupport::delete_data error %d\n",
                retcode);
    }

    // Delete all entities (DataWriter, Topic, Publisher, DomainParticipant)
    return shutdown(participant, "shutting down", 0);
}

// Delete all entities
static int shutdown(
        DDSDomainParticipant *participant,
        const char *shutdown_message,
        int status)
{
    DDS_ReturnCode_t retcode;

    printf("%s\n", shutdown_message);

    if (participant != NULL) {
        // This includes everything created by this Participant, including
        // DataWriters, Topics, Publishers. (and Subscribers and DataReaders)
        retcode = participant->delete_contained_entities();
        if (retcode != DDS_RETCODE_OK) {
            fprintf(stderr, "delete_contained_entities error %d\n", retcode);
            status = -1;
        }

        retcode = DDSTheParticipantFactory->delete_participant(participant);
        if (retcode != DDS_RETCODE_OK) {
            fprintf(stderr, "delete_participant error %d\n", retcode);
            status = -1;
        }
    }

    // Releases the memory used by the participant factory.
    retcode = DDSDomainParticipantFactory::finalize_instance();
    if (retcode != DDS_RETCODE_OK) {
        fprintf(stderr, "finalize_instance error %d\n", retcode);
        status = -1;
    }

    return status;
}

int main(int argc, char *argv[])
{
    // Parse arguments
    int domain_id = 0;
    if (argc >= 2) {
        domain_id = atoi(argv[1]);
    }

    int sample_count = 0;  // Infinite loop
    if (argc >= 3) {
        sample_count = atoi(argv[2]);
    }

    // Uncomment this to turn on additional logging
    // NDDSConfigLogger::get_instance()->
    // set_verbosity_by_category(NDDS_CONFIG_LOG_CATEGORY_API,
    // NDDS_CONFIG_LOG_VERBOSITY_STATUS_ALL);

    return publisher_run(domain_id, sample_count);
}

